### ISSUE TITLE
你的邮箱已爆表 无法联系

### ISSUE THREAD

**Issue by SangKa** [moreJs/RXjs-small#1]

**Comment by moreJs** [comment]
@SangKa sorry, 我才看到。 xgrommx/rx-book#65, 之前也想做和你类似的事情，但是作者没同意 ，所以搁浅了，正好前几天看到 Rxjs-cn，这个组织，所以想加入，一起做 rxjs 中文社区。

**Comment by SangKa** [comment]
好啊 欢迎一起来把RxJS中文社区搞起来
加qq群 601808192 咱们详聊
